meteor add accounts-base
 meteor add accounts-password
 meteor add accounts-ui
 meteor add alanning:roles
 meteor add aldeed:autoform
 meteor add aldeed:autoform-bs-datepicker
 meteor add aldeed:collection2
 meteor add aldeed:simple-schema
 meteor add appointment
 meteor add avatar
 meteor add chart:chart
 meteor add chhib:morris
 meteor add d3
 meteor add dburles:google-maps
 meteor add diagnose
 meteor add elevatedevdesign:autoform-nouislider
 meteor add email
 meteor add gquemart:meteor-reactive-fullcalendar
 meteor add insecure
 meteor add jplack:bootstrap-timepicker
 meteor add meteor-platform
 meteor add mirrorcell:geolocation-plus
 meteor add mizzao:bootstrap-3
 meteor add mizzao:jquery-ui
 meteor add mrt:moment
 meteor add msavin:mongol
 meteor add npm-bcrypt
 meteor add pfafman:font-awesome-4
 meteor add reactive-var
 meteor add sacha:spin
 meteor add styling
 meteor add userman
 meteor add vsivsi:job-collection
 meteor add yogiben:autoform-map

